language:
    - java

jdk:
    - openjdk6

before_install:
    - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://services.gradle.org/distributions/gradle-1.9-bin.zip
    - unzip -qq gradle-1.9-bin.zip
    - export GRADLE_HOME=`pwd`/gradle-1.9
    - export PATH=$GRADLE_HOME/bin:$PATH
    - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
    - tar -zxf android-sdk_r22.3-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo yes | android update sdk -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-18 --force --no-ui
    - wget http://dl.google.com/android/repository/build-tools_r19.0.1-linux.zip
    - mkdir -p $ANDROID_HOME/build-tools
    - unzip -qq build-tools_r19.0.1-linux.zip -d $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/build-tools/android-4.4.2 $ANDROID_HOME/build-tools/19.0.1

script:
    - "./gradlew"
    - "./gradlew test"

install: true

after_success:
    - CUR=`pwd`| echo $CUR

env:
  global:
    secure: fgBkKZYhXGiJSetWJOtEyK8KRELO7exYGl2W0+rSPlFgEcD3+5eW5qfIBuY4qK3lYDH24b5YkPxVoprAS6qnZbg8GQQVzVyWqzUwTr5qgSCbsPEuqptIDPjU6+42V20Gy/ABUtjSurgtqBff9ByQWpx6rEYZSX/LqTcxhqG2vuI=
